# Generated by Django 5.1.2 on 2024-10-12 09:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_alter_cruise_image_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/'), upload_to='cruises/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/'), upload_to='destinations/'),
        ),
    ]
