# Generated by Django 5.1.2 on 2024-10-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_alter_cruise_image_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='cruises', to='relecloud.destination'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cruises/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
